### ISSUE TITLE
Cannot-pipe-some-expressions can be solved with `$()`

### ISSUE THREAD

**Issue by ChaseFlorell** [nightroman/PowerShellTraps#1]
Just wanted to mention that the examples you have for `Cannot-pipe-some-expressions` are only incorrect because they're syntactically incorrect.
### solution

```
$result = foreach($e in 1..5) {$e}
$result | %{"Result is $_"}

'-------------------'

$(foreach($e in 1..5) {$e}) | %{"Result is $_"}

'-------------------'

$(foreach($e in 1..5) {$e}) > z.log

notepad z.log
```

**Comment by ChaseFlorell** [comment]
It can also be written as such.

```
(1..5) | %{"Result is $_"}
```

**Comment by ChaseFlorell** [comment]
haha, and there it is, I didn't notice your ['workaround'](https://github.com/nightroman/PowerShellTraps/blob/master/Basic/Cannot-pipe-some-expressions/.test.ps1#L17) in the tests.

**Comment by nightroman** [comment]
RTFM :)

Thank you for the feedback in any case. Perhaps the workarounds should be right in the README. I'll think of it.

**Comment by ChaseFlorell** [comment]
It's actually the only one I looked at in your repo. Was browsing it from a SO link. It probably would benefit having workarounds in the readme though :). 
For this case, however, it's not a workaround, as it's incorrect piping to do it the way it's done in the example since you need to always pipe a single object.

**Comment by nightroman** [comment]
Done, the workarounds are in README.

> PS Where is TFM? o_O
- The README says that in the 1st case it is a syntax error, and the 2nd case it is a missing command
- Workarounds were mentioned in the README as _.test.ps1 tests the above and shows some workarounds_. Now I removed this line.

**Comment by nightroman** [comment]
> For this case, however, it's not a workaround

Why not? It is a work around the incorrect syntax (and strange PowerShell design, too)

**Comment by ChaseFlorell** [comment]
> Why not? It is a work around the incorrect syntax.

haha, tou·ché
