### ISSUE TITLE
Resolution: Class/Cannot-derive-from-dot-sourced/README.md

### ISSUE THREAD

**Issue by morsley** [nightroman/PowerShellTraps#10]
In cases where a type is unknown to a file at parse-time, you can utilize `Invoke-Expression` of the class definition to work around this hindrance.

**Comment by nightroman** [comment]
@TheIncorrigible1 Thank you! I'll take a closer look next week and update the topic.

**Comment by morsley** [comment]
This is a common pattern I follow with `using namespace` or `Add-Type` statements to make code a little cleaner:

```powershell
using namespace System.Net

Invoke-Expression -Command @'
class MyClass : ICertificatePolicy {
    <# ... #>
}
'@
```

**Comment by nightroman** [comment]
Done, see updated [Cannot-derive-from-dot-sourced](https://github.com/nightroman/PowerShellTraps/tree/master/Class/Cannot-derive-from-dot-sourced)
