### ISSUE TITLE
Potential collaboration with pwsh-live-doc

### ISSUE THREAD

**Issue by binyomen** [nightroman/PowerShellTraps#12]
Hey!

A bit ago I created https://github.com/benweedon/pwsh-live-doc/ to document the dark corners of PowerShell by automatically running examples and generating a web site from them.

Today I found this repository, which is absolutely amazing! I didn't realize such a large repository of PowerShell quirks existed.

I was wondering if we could discuss some potential collaboration. I just finished the bulk of the generation logic for my site and so I'm just getting started adding more examples. I'd love to migrate things from here to my repo (and link back here of course). I'd also be curious if you can think of any ways for this repo to make use of mine. For example, my project could become a more generic PowerShell documentation generation engine, and yours could host the actual documentation and generate a site from it.

I feel like both our projects are pretty similar, and it would be great to share the load a bit. What are your thoughts?

**Comment by nightroman** [comment]
Hi @benweedon , feel free to use any examples from this repo, this is the idea
of it, to spread awareness of issues. And if you do not mind, I'll borrow some
cases from your collection, too.

To be honest, I am not sure about merging. Of course this would be nice. But my
available time is limited. I am supporting and evolving PowerShellTraps, on my
own schedule. This works well so far, I do not want to change anything, even if
some "better" format of representation is possible. The current format (topics,
examples, tests of examples) is reasonably good and it is a "site" out of the
box (even though GitHub shaped, not a true site).

**Comment by binyomen** [comment]
This sounds good to me :). Honestly, the more I think about it the more unmanagable maintaining a generic documentation engine in my free time sounds anyway.

I can also submit PRs here if I find anything that's missing. I don't have much for you to borrow at the moment, but I'm sitting on a large backlog of examples I want to add so once that's all up there will hopefully be much more :)

**Comment by nightroman** [comment]
> I can also submit PRs here if I find anything that's missing ...

That would be great!
Or simply post suggestions (issues) here if you do not have time for PRs.
