### ISSUE TITLE
Is "*.ext matches *.ext*" related to 8.3 names?

### ISSUE THREAD

**Issue by jingyu9575** [nightroman/PowerShellTraps#16]
In *Provider specific filters*, it is stated that "\*.ext where ext is three characters matches \*.ext\*". 
This reminds me of a legacy Windows feature: on some systems, files with long names or extensions get a 8.3 name for DOS compatibility. For example, a file "application.docx" may get a short name "applic~1.doc" and matches \*.doc. This feature can be controlled by the [fsutil command](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil-8dot3name).
Do you think this is the reason?

**Comment by nightroman** [comment]
Yes, I think this might be the reason, directly or related. Some obsolete and probably related API is still in use. Maybe for some compatibility, maybe it's actually good. Thank you for the info about `fsutil`, it's new to me. Of course it cannot fix the issue as such for us, PS scripts/tools writers. Scripts cannot count on the issue "fixed", ideally they should work on any machine.
