### ISSUE TITLE
A provider path passed *positionally* fails to make dynamic parameters available if it is placed *after* the dynamic parameter

### ISSUE THREAD

**Issue by God-damnit-all** [nightroman/PowerShellTraps#18]
via [PowerShell/PowerShell #19495](https://www.github.com/PowerShell/PowerShell/issues/19495) by [mklement0](https://github.com/mklement0):

> A common idiom is to do something like `Get-ChildItem -Directory $somePath`.
> 
> This works fine if the provider underlying the current location happens to be the file-system provider, but fails otherwise.
> 
> Seemingly, the dynamic `-Directory` parameter is searched for _before_ the _positional_ path argument is bound (which is necessary to infer the provider context). Placing the dynamic parameter _after_ the positional path argument fixes the problem, as does using a _named_ argument to pass the path (`-Path $somePath` or `-LiteralPath $somePath`).
> 
> ```powershell
> Push-Location function:  # change to a non-file-system location
> # !! Fails to find -Directory - by contrast, the following DO work:
> #    * Get-ChildItem $PSHOME -Directory  # positional argument comes *first*
> #    * Get-ChildItem -Directory -Path $PSHOME  # *named* argument
> Get-ChildItem -Directory $PSHOME
> Pop-Location
> ```
> 
> #### Expected behavior
> A listing of the subdirectories of the `$PSHOME` directory.
> 
> #### Actual behavior
> ```
> Get-ChildItem: A parameter cannot be found that matches parameter name 'Directory'.
> ```

---

Confirmed on PowerShell 5.1 all the way through 7.4-preview.3

Unknown if this affects versions of PowerShell before 5.1

**Comment by nightroman** [comment]
@ImportTaste Thank you, it looks like a good addition to the collection. I'll follow up later when I am back from holiday.

The nature of this issue might be similar to described here -- [PowerShellTraps/Basic/DynamicParam/Dynamic-switch-parameter](https://github.com/nightroman/PowerShellTraps/tree/main/Basic/DynamicParam/Dynamic-switch-parameter)

The dynamic switch `-Directory` "swallows" the following argument `$PSHOME` and that's probably why PS "does not know" that it is the file system path and provider.

**Comment by nightroman** [comment]
I have added the link to the new known issue to the existing topic. I think nothing else is needed because the issue is already covered, it's just another example. Thank you for reporting it though, it's all useful.

**Comment by nightroman** [comment]
> Unknown if this affects versions of PowerShell before 5.1

I believe the issue is there since the very introduction of dynamic parameters, i.e. PS v3+.

**Comment by God-damnit-all** [comment]
Good to know, thank you.

> I have added the link to the new known issue to the existing topic. I think nothing else is needed because the issue is already covered, it's just another example. Thank you for reporting it though, it's all useful.

Ah, I see. Well, I'm glad you're receptive to it, I was a bit hesitant to copy-and-paste an issue from another repo, but it seemed like exactly the sort of trap you'd be interested in covering.

As an aside, are you part of the PowerShell Discord server?

**Comment by nightroman** [comment]
> As an aside, are you part of the PowerShell Discord server?

No.

**Comment by God-damnit-all** [comment]
Ah well.
