### ISSUE TITLE
`Get-Content -OutVariable var -ReadCount 0 -Raw` Nested array On `$var`

### ISSUE THREAD

**Issue by mattcargile** [nightroman/PowerShellTraps#19]
```powershell
New-Item sysObject.txt -value "hello`r`nworld"
Get-Content sysObject.txt -Raw -ReadCount 0 -OutVariable var | Out-Null
$var -join ','
Remove-Item sysObject.txt
```
This produces `System.Object[0]` as a `[string]`. Removing the `-ReadCount 0` fixes the issue. This works on _7.4.5_ and _5.1.22621.3958_

**Comment by nightroman** [comment]
@mattcargile Thank you. I'll play with this and add a new trap case.

**Comment by nightroman** [comment]
Here it is -- https://github.com/nightroman/PowerShellTraps/tree/main/Cmdlets/Get-Content/OutVariable-and-ReadCount
