### ISSUE TITLE
[suggested trap] Weird null-ness

### ISSUE THREAD

**Issue by SergeyTeplyakov** [nightroman/PowerShellTraps#2]
Maybe this is already in your list, but just in case.

Consider following two cases:

```
$tmp = (1..5 | where {$_ -gt 6} | select -First 1)
$list1 = @(, $tmp)
$list1.Length # 0

$list2 = @(, $(if($tmp -eq $null) {$null} else {$tmp}))
$list2.Length # 1

```

To create an array with one element from piped expression additional magic step is required.

In first case `list1` is an empty array, but in the second case it has one element equals to `$null`.

This is really strange for me, because for me expression like `$(if($tmp -eq $null) {$null} else {$tmp})` is equivalent to `$tmp`.

P.S. I've found this issue trying to create closures in PowerShell. Because closures captures outer variable by value you have to wrap captured variable in array or another mutable instance. But that's another story.

**Comment by nightroman** [comment]
Thank you, this is a good one and it is not in the list. I am thinking of some simplified demo like this:

``` powershell
# is $it null or what?
$it = (1..5 | Where-Object {$_ -gt 6})

# gets $true, so $it looks like null
$null -eq $it

# but this gets 0
$list1 = @(, $it)
$list1.Length

# and this gets 1
$list2 = @(, $null)
$list2.Length
```

Just to be sure: is it the issue you are talking about or slightly different?

I will think of some explanation and practical tips perhaps. But this case should be added, of course.

**Comment by nightroman** [comment]
Or maybe this is better, variables are used in both cases

``` powershell
# is $it1 null or what?
$it1 = (1..5 | Where-Object {$_ -gt 6})

# gets $true, so $it1 looks like null
$null -eq $it1

# $it2 is definitely null
$it2 = $null

# but this gets 0 with $it1
$list1 = @(, $it1)
$list1.Length

# and this gets 1 with $it2
$list2 = @(, $it2)
$list2.Length
```

I am also thinking of a title. "Different kind of nulls", perhaps? "Nothing is not exactly null"?

**Comment by nightroman** [comment]
> This is really strange for me, because for me expression like $(if($tmp -eq $null) {$null} else {$tmp}) is equivalent to $tmp.

This expression gets `$null` because `$tmp -eq $null` gets true, see my test. And we can see that `$null` is not the same as "nothing". "nothing" means not empty array but no results. Yes, all this is very interesting.

I have found one more clue on what "nothing" is. But I will investigate this later, got to go now.

**Comment by SergeyTeplyakov** [comment]
About practical scnario: I've faced this issue when I tried to use closures in PowerShell.

I tried to create a helper function that will set a conditional breakpoint based on number of hits:

``` powershell
<#
.SYNOPSIS
Sets conditional breakpoint

.EXAMPLE
Set-Breakpoint -HitCount 3 -Script "Set-Breakpoint.ps1" -Action {Write-Host "Breakpoint was called!!!"} -LineNumber 5
#>
Function Set-Breakpoint
{
    [CmdletBinding()]
    param(
        [int]$HitCount = 1,
        [string]$Script,
        [int]$LineNumber,
        [scriptblock]$Action,
        [switch]$NeedBreak)

    $verboseEnabled = $PSBoundParameters['Verbose']

    # Captured variable should be an array, not a scalar
    $breakpoint = (, (Get-PSBreakpoint -Script $Script | Where {$_.Line -eq $LineNumber} | select -First 1))

    $customAction = { 
        if ( $script:breakpoint[0].HitCount -ne 0 -and ($script:breakpoint[0].HitCount % $HitCount) -eq 0)
        {
            $script:Action.Invoke()
            if ($script:NeedBreak) { break }
        }
    }.GetNewClosure()

    if (!$breakpoint[0])
    {
        Set-PSBreakpoint -Script $Script -Line $LineNumber -Action $customAction -Verbose:$verboseEnabled
        # Getting breakpoint, to be able to use it in the closure
        $breakpoint[0] = (Get-PSBreakpoint -Script $Script | Where {$_.Line -eq $LineNumber} | select -First 1)
    }
}
```

And I've made an error in line `$breakpoint = (, (Get-PSBreakpoint...`. I used `@(, Get)` instead of plain `(, Get)`. In this case I started getting OutOfRange errors and stared at this code for 20 minutes trying to find out what the hell is going on. 

So this issue has practical background.

**Comment by SergeyTeplyakov** [comment]
Another interesting point here:

``` powershell
$lst = (1..5 | where {$_ -gt 6})
$lst.Length
```

Actually this code will fail with following error: 'The property 'Length' cannot be found on this object. Verify that the property exists.'. This means that empty sequence in PowerShell is much closer to `$null` that I thought initially! You can update you example to show, that `$it1` in your example is not an empty sequence per se, because you can't check the length or type of this thing.

> I am also thinking of a title. "Different kind of nulls", perhaps? "Nothing is not exactly null"?

"Different kind of nulls" sounds good for me. At least for now, maybe we'll find another corner cases that will affect the name of this trap.

**Comment by SergeyTeplyakov** [comment]
And, by the way, another trap: empty array from `where` commandlet is not the same as an empty array from `@()` expression:

``` powershell
$list3 = @(, @())
$list3.Length # 1 (!)
```

And even more fun with null-ness:

``` powershell
@() -eq $null # nothing! The result itself is $null!
$null -eq $null # $True!
```

So the behavior even more weird that I thought at the beginning:)

**Comment by nightroman** [comment]
> @() -eq $null

It's OK. You have been trapped :) See [Logical-operators-with-collections](https://github.com/nightroman/PowerShellTraps/tree/master/Basic/Logical-operators-with-collections).

**Comment by nightroman** [comment]
Some results so far:
- The mysterious "nothing-null" is actually not null, see the code below.
- In PS v2 "nothing-null" is null. I.e. `$listX.Length` is 1 in both cases.

``` powershell
    # is $it1 null or what?
    $it1 = (1..5 | Where-Object {$_ -gt 6})

    # gets $true, so $it1 looks like null
    $null -eq $it1

    # False
    $null -eq $it1.PSObject

    # System.Management.Automation.PSCustomObject
    $it1.PSObject.BaseObject.GetType().FullName
```

> ... So this issue has practical background.

Of course. I did not mean this issue is academic. By "practical tips" I meant
"workarounds", i.e. ways to distinguish such nulls. Perhaps one is found above.

**Comment by SergeyTeplyakov** [comment]
> It's OK. You have been trapped :) See Logical-operators-with-collections.

Thanks! I've forgot about this behavior!

**Comment by nightroman** [comment]
It is pushed as [Different-kinds-of-null](https://github.com/nightroman/PowerShellTraps/tree/master/Basic/Different-kinds-of-null).

If you think it explains the issue well please close it. Otherwise, feel free to comment and suggest changes or additions. I am going to watch this issue anyway, it would be interesting to find more cases where nothing-null is different or causes problems.
