### ISSUE TITLE
When require path separator mark for directory path. Join-Path does not work

### ISSUE THREAD

**Issue by ZSkycat** [nightroman/PowerShellTraps#20]
https://github.com/PowerShell/PowerShell/issues/24193

**Comment by nightroman** [comment]
Hi @ZSkycat Thank you for the suggestion.

I am not sure how to present this issue. This trap collection is not a
PowerShell bug tracker as such, PowerShell has its own, we do not just
duplicate issues here.

There should be a story of doing something "normal" and getting something
"unexpected" which results in problems in practice. Your case is doing
something "unusual".

Using path like `\`, `/`, `\path` or `/path` as the second argument of
`Join-Path` is not normal, IMHO. The normal use case is a relative path.
These paths are not relative.

**Comment by ZSkycat** [comment]
From my perspective, `Join-Path` is simply concatenates path and path2 and adds a directory separator character between any of the path components if one is not already present. It mainly solves the problem of slash and backslash and has nothing to do with relative paths.

There is no use using it like this:

```
> Join-Path $PWD.ProviderPath '.\'
C:\pwd\.\
```

For example:

Some applications require path separator mark for directory path. Like `7z.exe -spm`. "PowerShell" as a wrapper for the application, needs to correct user input.

`Join-Path $UserInputPath '\'` used for this purpose.

The file system supports slash and backslash paths. The user may enter a different slash than the default. This will lead to unexpected results.

```
Join-Path 'C:/Test/Test/' '\'
> C:/Test/Test/\
```

This problem only occurs when join `/` or `\`.

In addition, `Join-Path` fails if the path drive does not exist. related issues https://github.com/PowerShell/PowerShell/issues/20011#issuecomment-1646664012

**Comment by nightroman** [comment]
I see. And it used to works (or still works) in PS Desktop and stopped working as expected in PS Core, right? That would be a "trap" case, sure.

**Comment by ZSkycat** [comment]
Yes. It works in Windows PowerShell.

**Comment by nightroman** [comment]
@ZSkycat Here is the draft
https://github.com/nightroman/PowerShellTraps/tree/2024-10-03-0245/Cmdlets/Join-Path/With-path-separator

So far I have provided just one case, see `Test-1.ps1`, it is from your last comment above.
What other cases would like to see in this script? Not too many, please, and not too contrived.

**Comment by ZSkycat** [comment]
```
# 5.1 : Test\Test\
# 7.x : Test/Test/\
Join-Path 'Test/Test/' '/'
```

**Comment by nightroman** [comment]
Done, thank you for the suggestion and help
https://github.com/nightroman/PowerShellTraps/tree/main/Cmdlets/Join-Path/With-path-separator
