### ISSUE TITLE
Powershell and lost exception origins

### ISSUE THREAD

**Issue by SergeyTeplyakov** [nightroman/PowerShellTraps#3]
I've found another trap in PowerShell.

Consider following code:

``` powershell
Set-StrictMode -Version Latest

Function WillThrow
{
    $result = "Some string $UnknownVariable"
}

Function WillCatchAndRethrow
{
    Try
    {
        WillThrow
    }
    catch
    {
        #Write-Host "Yep, we failed! Rolling back some stuff!" 
        throw
    }
}

WillCatchAndRethrow
```

This is a very simplified version of production code where `WillCatchAndRethrow` is doing some simple recovery like rolling back transaction. This script will fail, obviously, with following error

```
The variable '$UnknownVariable' cannot be retrieved because it has not been set.
At line:7 char:28
+     $result = "Some string $UnknownVariable"
+                            ~~~~~~~~~~~~~~~~
```

So far so good. But lets change `WillThrow` function a little bit:

``` powershell
Function WillThrow
{
    [CmdletBinding()]
    param()
    $result = "Some string $UnknownVariable"
}
```

I've added a `CmdletBinding` attribute because I need some stuff that this attribute provides. Lets rerun this script once again. It will still fail, but look carefully at error message:

```
WillThrow : The variable '$UnknownVariable' cannot be retrieved because it has not been set.
At line:14 char:9
+         WillThrow
+         ~~~~~~~~~
```

Ooops! Now we've lost critical information about the error: it's origin!

**Comment by nightroman** [comment]
I have seen this issue, too. I will think of adding it to the list. Note that v2 works as expected. Workaround: in such cases (if possible) I check the variable `$Error`. It often contains an error with correct information. I.e. run your script in the interactive console and then after the failure type `$Error`.

**Comment by nightroman** [comment]
I have pushed it as [Misleading-error-location](https://github.com/nightroman/PowerShellTraps/tree/master/Basic/Misleading-error-location). If it looks fine please close the issue.

In the future it would be useful to collect and add some different examples.
