### ISSUE TITLE
if statement is crazy

### ISSUE THREAD

**Issue by SergeyTeplyakov** [nightroman/PowerShellTraps#6]
Another crazyness related to if statement.

Suppose we have an optional array:

``` powershell
$ar = (1, 2, 3)
```

And, suppose that we would like to create some default array if `$ar` is empty (yep, we'll try to emulate null-coalescing operator from C#):

``` powershell
$ar1 = if ($ar) {$ar} else {(1, 2)}
```

Ok, looks good, but what if we would like not only "coalesce" an array, but also to convert a result to, for instance, array of strings:

``` powershell
$ar2 = [string[]](if ($ar) {$ar} else {(1, 2)})
```

Unfortunately, this code fails with an error:

```
if : The term 'if' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

There is two ways to solve this problem. 

Use two different statements:

``` powershell
$tmp = if ($ar) {$ar} else {@(1, 2, 3)}
$ar2 = [string[]]($tmp)
```

Or by introducing temporary variable inside if statement:

``` powershell
$ar3 = [string[]]($tmp = if ($ar) {$ar} else {@(1, 2, 3)})
```

Again, I do think this is yet another bug rather than a trap!

**Comment by nightroman** [comment]
It is probably not a bug but a trap, indeed. I think it has the same roots as [Cannot-pipe-some-expressions](https://github.com/nightroman/PowerShellTraps/tree/master/Basic/Cannot-pipe-some-expressions). It's more likely that `for`, `foreach`, and other assignable statements work (do not work) in the same way. The workaround is use of `$(...)`, not just `(...)`.

This case probably should be mentioned, too. I'll think of this.

**Comment by SergeyTeplyakov** [comment]
Hm... I don't see any pipes in my case... Maybe this is related, but this behavior is strange it terms of what PowerShell treats as an expression. For instance, why `$(if ..)` is behave differently from `($tmp = if ..)`? Maybe there is some rationale behind this and in this case it is a trap.

On the other hand, subexpressions for `$(if..)` sounds like a workaround for a bug, because by definition subexpression for one expression should do nothing.

**Comment by nightroman** [comment]
`if`, and others with keywords, are statements, not expressions. In v1 they could not be even assigned. In v2+ they can be assigned. This is probably a good feature. With a cost, as usual. It created an illusion that statements are expressions, as far as they can be assigned. Pipeline and redirection described in the trap are two cases of this fact. Your case is another one.

I think we should rename Cannot-pipe-some-expressions to something like "Statements-are-not-expressions" and add more examples.

**Comment by nightroman** [comment]
`()` is for expressions only. But `if` is not expression. So it's "fine" that `()` does not work. It's not fine that a user may not expect this.

`$()` is for any code, even for 2+ statements, not just one with `if`.

**Comment by SergeyTeplyakov** [comment]
Ok, now I got it! I thought that PowerShell is expression-based language because you can assign `$foo = if {...}`. In any other programming language this means that `if` is an expression and can be used in any other place where expression is used.

Yep, proposed rename sounds good for me. It will sounds like a general trap rather than something particular.

**Comment by nightroman** [comment]
Renamed the case _Cannot-pipe-some-expressions_ to [Statements-are-not-expressions](https://github.com/nightroman/PowerShellTraps/tree/master/Basic/Statements-are-not-expressions).  Reviewed its content and added some new facts.
